OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
	.string "Cuando empieza un combáte POKéMON,\n"
	.string "el que está a la izquierda de la lista\n"
	.string "sale a luchar primero.\p"
	.string "Así que, cuando tengas varios POKéMON\n"
	.string "en tu equipo, prueba a cambiar de orden.\p"
	.string "En algunos casos, podría darte ventaja.$"
